[workspace]

# Remember to also update the project's Cargo.toml
# if it's a top-level project
members = [
    "atiadlxx-sys",
    "comgr",
    "cuda_base",
    "cuda_types",
    "detours-sys",
    "ext/llvm-sys.rs",
    "hip_common",
    "hip_runtime-sys",
    "hipblaslt-sys",
    "hipfft-sys",
    "hiprt-sys",
    "hiprtc-sys",
    "miopen-sys",
    "offline_compiler",
    "optix_base",
    "optix_dump",
    "process_address_table",
    "ptx",
    "rocblas-sys",
    "rocm_smi-sys",
    "rocsparse-sys",
    "xtask",
    "zluda",
    "zluda_api",
    "zluda_blas",
    "zluda_blaslt",
    "zluda_ccl",
    "zluda_dark_api",
    "zluda_dnn",
    "zluda_dump",
    "zluda_fft",
    "zluda_inject",
    "zluda_lib",
    "zluda_llvm",
    "zluda_ml",
    "zluda_redirect",
    "zluda_rt",
    "zluda_rtc",
    "zluda_sparse",
]

# Cargo does not support OS-specific or profile-specific
# targets. We keep list here to bare minimum and rely on xtask
default-members = [
    "zluda_lib",
    "zluda_ml",
    "zluda_inject",
    "zluda_redirect"
]

[profile.dev.package.blake3]
opt-level = 3

[profile.dev.package.lz4-sys]
opt-level = 3

[profile.dev.package.xtask]
opt-level = 2
