[package]
name = "zluda_inject"
version = "3.9.5"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2018"

[[bin]]
name = "zluda"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["jobapi", "jobapi2", "processenv", "processthreadsapi", "synchapi", "winbase", "std"] }
tempfile = "3"
argh = "0.1"
detours-sys = { path = "../detours-sys" }

[dev-dependencies]
# all of those are used in integration tests
zluda_redirect = { path = "../zluda_redirect" }
zluda_dump = { path = "../zluda_dump" }
zluda_ml = { path = "../zluda_ml" }

[build-dependencies]
embed-manifest = "1.3.1"

[package.metadata.zluda]
windows_only = true
